-- -----------------------------------------------------------------------------------
--  Program Name:   create_mysql_tables.sql
--  Program Author: Cory Larcade
--  Creation Date:  15-APR-2014
--  Description: This script creates all of the essential tables for Garry's database.
-- -----------------------------------------------------------------------------------

-- Choose the database.
USE garrydb;

-- Open log file.
TEE create_mysql_tables.log

-- This enables dropping tables with foreign key dependencies.
-- It is specific to the InnoDB Engine.
SELECT 'OFF' AS "FOREIGN KEY CHECKS";
SET FOREIGN_KEY_CHECKS = 0; 

-- Conditionally drop objects.
SELECT 'SYSTEM_USER' AS "Drop Table";
DROP TABLE IF EXISTS SYSTEM_USER;

-- ------------------------------------------------------------------
-- Create SYSTEM_USER table.
-- ------------------------------------------------------------------
SELECT 'SYSTEM_USER' AS "Create Table";
CREATE TABLE SYSTEM_USER
( SYSTEM_USER_ID   INT UNSIGNED AUTO_INCREMENT
, MEMBER_ID        INT UNSIGNED
, SYSTEM_USER_TYPE INT UNSIGNED NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_system_user_1 PRIMARY KEY (SYSTEM_USER_ID)
, CONSTRAINT fk_system_user_1 FOREIGN KEY (MEMBER_ID)        REFERENCES MEMBER(MEMBER_ID)
, CONSTRAINT fk_system_user_2 FOREIGN KEY (SYSTEM_USER_TYPE) REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_system_user_3 FOREIGN KEY (CREATED_BY)       REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_system_user_4 FOREIGN KEY (LAST_UPDATED_BY)  REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT 'SYSTEM_USER' AS "INSERT INTO";
INSERT INTO SYSTEM_USER
( SYSTEM_USER_ID
, MEMBER_ID
, SYSTEM_USER_TYPE
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( NULL
, 1 -- 1st Entry in MEMBER table
, 2 -- 'DBA'
, 1, UTC_DATE(), 1, UTC_DATE());

-- Conditionally drop objects.
SELECT 'COMMON_LOOKUP' AS "Drop Table";
DROP TABLE IF EXISTS COMMON_LOOKUP;

-- ------------------------------------------------------------------
-- Create COMMON_LOOKUP table.
-- ------------------------------------------------------------------
SELECT 'COMMON_LOOKUP' AS "Create Table";
CREATE TABLE COMMON_LOOKUP
( COMMON_LOOKUP_ID      INT UNSIGNED AUTO_INCREMENT
, COMMON_LOOKUP_TYPE    CHAR(30)     NOT NULL
, COMMON_LOOKUP_MEANING CHAR(30)     NOT NULL
, COMMON_LOOKUP_TABLE   VARCHAR(30)  NOT NULL
, COMMON_LOOKUP_COLUMN  VARCHAR(30)  NOT NULL
, CREATED_BY            INT UNSIGNED NOT NULL
, CREATION_DATE         DATE         NOT NULL
, LAST_UPDATED_BY       INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE      DATE         NOT NULL
, CONSTRAINT pk_common_lookup_1 PRIMARY KEY (COMMON_LOOKUP_ID)
, CONSTRAINT ui_common_lookup_1 UNIQUE INDEX (COMMON_LOOKUP_TABLE, COMMON_LOOKUP_COLUMN, COMMON_LOOKUP_TYPE) USING BTREE
, CONSTRAINT fk_common_lookup_1 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_common_lookup_2 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'SYSTEM_ADMIN'
, 'System Administrator'
, 'SYSTEM_USER'
, 'SYSTEM_USER_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'DBA'
, 'Database Administrator'
, 'SYSTEM_USER'
, 'SYSTEM_USER_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'EMPLOYEE'
, 'Employee'
, 'CONTACT'
, 'CONTACT_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'CUSTOMER'
, 'Customer'
, 'CONTACT'
, 'CONTACT_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'INDIVIDUAL'
, 'Individual Membership'
, 'MEMBER'
, 'MEMBER_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'HOME'
, 'Home address'
, 'ADDRESS'
, 'ADDRESS_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'WORK'
, 'Work address'
, 'ADDRESS'
, 'ADDRESS_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'HOME'
, 'Home telephone'
, 'TELEPHONE'
, 'TELEPHONE_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'WORK'
, 'Work telephone'
, 'TELEPHONE'
, 'TELEPHONE_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'SPORT'
, 'Sport'
, 'INTEREST'
, 'INTEREST_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'MOVIE'
, 'Movie'
, 'INTEREST'
, 'INTEREST_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'HOBBY'
, 'Hobby'
, 'INTEREST'
, 'INTEREST_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'DISCOVER_CARD'
, 'Discover Card'
, 'MEMBER'
, 'CREDIT_CARD_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'MASTER_CARD'
, 'Master Card'
, 'MEMBER'
, 'CREDIT_CARD_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

SELECT 'COMMON_LOOKUP' AS "INSERT INTO";
INSERT INTO COMMON_LOOKUP
( COMMON_LOOKUP_TYPE
, COMMON_LOOKUP_MEANING
, COMMON_LOOKUP_TABLE
, COMMON_LOOKUP_COLUMN
, CREATED_BY
, CREATION_DATE
, LAST_UPDATED_BY
, LAST_UPDATE_DATE
)
VALUES
( 'VISA_CARD'
, 'VISA Card'
, 'MEMBER'
, 'CREDIT_CARD_TYPE'
, 1, UTC_DATE(), 1, UTC_DATE());

-- Conditionally drop objects.
SELECT 'MEMBER' AS "Drop Table";
DROP TABLE IF EXISTS MEMBER;

-- ------------------------------------------------------------------
-- Create MEMBER table.
-- ------------------------------------------------------------------
SELECT 'MEMBER' AS "Create Table";
CREATE TABLE MEMBER
( MEMBER_ID          INT UNSIGNED AUTO_INCREMENT
, PARENT_MEMBER_ID   INT UNSIGNED
, ACCOUNT_NUMBER     CHAR(10)
, CREDIT_CARD_NUMBER CHAR(19)
, CREDIT_CARD_TYPE   INT UNSIGNED
, MEMBER_TYPE        INT UNSIGNED NOT NULL
, CREATED_BY         INT UNSIGNED NOT NULL
, CREATION_DATE      DATE         NOT NULL
, LAST_UPDATED_BY    INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE   DATE         NOT NULL
, CONSTRAINT pk_member_1 PRIMARY KEY (MEMBER_ID)
, CONSTRAINT fk_member_1 FOREIGN KEY (PARENT_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
, CONSTRAINT fk_member_2 FOREIGN KEY (CREDIT_CARD_TYPE) REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_member_3 FOREIGN KEY (MEMBER_TYPE)      REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_member_4 FOREIGN KEY (CREATED_BY)       REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_member_5 FOREIGN KEY (LAST_UPDATED_BY)  REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'CONTACT' AS "Drop Table";
DROP TABLE IF EXISTS CONTACT;

-- ------------------------------------------------------------------
-- Create CONTACT table.
-- ------------------------------------------------------------------
SELECT 'CONTACT' AS "Create Table";
CREATE TABLE CONTACT
( CONTACT_ID       INT UNSIGNED AUTO_INCREMENT
, MEMBER_ID        INT UNSIGNED NOT NULL
, CONTACT_TYPE     INT UNSIGNED NOT NULL
, FIRST_NAME       CHAR(20)     NOT NULL
, MIDDLE_NAME      CHAR(20)
, LAST_NAME        CHAR(20)     NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_contact_1 PRIMARY KEY (CONTACT_ID)
, CONSTRAINT fk_contact_1 FOREIGN KEY (MEMBER_ID)       REFERENCES MEMBER(MEMBER_ID)
, CONSTRAINT fk_contact_2 FOREIGN KEY (CONTACT_TYPE)    REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_contact_3 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_contact_4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'EMAIL_ADDRESS' AS "Drop Table";
DROP TABLE IF EXISTS EMAIL_ADDRESS;

-- ------------------------------------------------------------------
-- Create EMAIL_ADDRESS table.
-- ------------------------------------------------------------------
SELECT 'EMAIL_ADDRESS' AS "Create Table";
CREATE TABLE EMAIL_ADDRESS
( EMAIL_ADDRESS_ID INT UNSIGNED AUTO_INCREMENT
, CONTACT_ID       INT UNSIGNED NOT NULL
, EMAIL            VARCHAR(10)  NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_email_1 PRIMARY KEY (EMAIL_ADDRESS_ID)
, CONSTRAINT fk_email_1 FOREIGN KEY (CONTACT_ID)      REFERENCES CONTACT(CONTACT_ID)
, CONSTRAINT fk_email_2 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_email_3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'ADDRESS' AS "Drop Table";
DROP TABLE IF EXISTS ADDRESS;

-- ------------------------------------------------------------------
-- Create ADDRESS table.
-- ------------------------------------------------------------------
SELECT 'ADDRESS' AS "Create Table";
CREATE TABLE ADDRESS
( ADDRESS_ID       INT UNSIGNED AUTO_INCREMENT
, CONTACT_ID       INT UNSIGNED NOT NULL
, ADDRESS_TYPE     INT UNSIGNED NOT NULL
, CITY             CHAR(30)     NOT NULL
, STATE_PROVINCE   CHAR(30)     NOT NULL
, POSTAL_CODE      CHAR(20)     NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_address_1 PRIMARY KEY (ADDRESS_ID)
, CONSTRAINT fk_address_1 FOREIGN KEY (CONTACT_ID)      REFERENCES CONTACT(CONTACT_ID)
, CONSTRAINT fk_address_2 FOREIGN KEY (ADDRESS_TYPE)    REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_address_3 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_address_4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'STREET_ADDRESS' AS "Drop Table";
DROP TABLE IF EXISTS STREET_ADDRESS;

-- ------------------------------------------------------------------
-- Create STREET_ADDRESS table.
-- ------------------------------------------------------------------
SELECT 'STREET_ADDRESS' AS "Create Table";
CREATE TABLE STREET_ADDRESS
( STREET_ADDRESS_ID INT UNSIGNED AUTO_INCREMENT
, ADDRESS_ID        INT UNSIGNED NOT NULL
, STREET_ADDRESS    CHAR(30)     NOT NULL
, CREATED_BY        INT UNSIGNED NOT NULL
, CREATION_DATE     DATE         NOT NULL
, LAST_UPDATED_BY   INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE  DATE         NOT NULL
, CONSTRAINT pk_street_address_1 PRIMARY KEY (STREET_ADDRESS_ID)
, CONSTRAINT fk_street_address_1 FOREIGN KEY (ADDRESS_ID)      REFERENCES ADDRESS(ADDRESS_ID)
, CONSTRAINT fk_street_address_2 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_street_address_3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'TELEPHONE' AS "Drop Table";
DROP TABLE IF EXISTS TELEPHONE;

-- ------------------------------------------------------------------
-- Create TELEPHONE table.
-- ------------------------------------------------------------------
SELECT 'TELEPHONE' AS "Drop Table";
CREATE TABLE TELEPHONE
( TELEPHONE_ID     INT UNSIGNED AUTO_INCREMENT
, CONTACT_ID       INT UNSIGNED NOT NULL
, ADDRESS_ID       INT UNSIGNED
, TELEPHONE_TYPE   INT UNSIGNED NOT NULL
, COUNTRY_CODE     CHAR(3)      NOT NULL
, AREA_CODE        CHAR(6)      NOT NULL
, TELEPHONE_NUMBER CHAR(10)     NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_telephone_1 PRIMARY KEY (TELEPHONE_ID)
, CONSTRAINT fk_telephone_1 FOREIGN KEY (CONTACT_ID)      REFERENCES CONTACT(CONTACT_ID)
, CONSTRAINT fk_telephone_2 FOREIGN KEY (ADDRESS_ID)      REFERENCES ADDRESS(ADDRESS_ID)
, CONSTRAINT fk_telephone_3 FOREIGN KEY (TELEPHONE_TYPE)  REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_telephone_4 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_telephone_5 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'INTEREST' AS "Drop Table";
DROP TABLE IF EXISTS INTEREST;

-- ------------------------------------------------------------------
-- Create INTEREST table.
-- ------------------------------------------------------------------
SELECT 'INTEREST' AS "Drop Table";
CREATE TABLE INTEREST
( INTEREST_ID      INT UNSIGNED AUTO_INCREMENT
, INTEREST_TYPE    INT UNSIGNED NOT NULL
, INTEREST_NAME    VARCHAR(30)  NOT NULL
, DESCRIPTION      VARCHAR(30)  NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_interest_1 PRIMARY KEY (INTEREST_ID)
, CONSTRAINT fk_interest_1 FOREIGN KEY (INTEREST_TYPE)   REFERENCES COMMON_LOOKUP(COMMON_LOOKUP_ID)
, CONSTRAINT fk_interest_2 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_interest_3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'USERNAME' AS "Drop Table";
DROP TABLE IF EXISTS USERNAME;

-- ------------------------------------------------------------------
-- Create USERNAME table.
-- ------------------------------------------------------------------
SELECT 'USERNAME' AS "Drop Table";
CREATE TABLE USERNAME
( USERNAME_ID      INT UNSIGNED AUTO_INCREMENT
, MEMBER_ID        INT UNSIGNED NOT NULL
, USERNAME         VARCHAR(10)  NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_username_1 PRIMARY KEY (USERNAME_ID)
, CONSTRAINT fk_username_1 FOREIGN KEY (MEMBER_ID)       REFERENCES MEMBER(MEMBER_ID)
, CONSTRAINT fk_username_2 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_username_3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'PASSWORD' AS "Drop Table";
DROP TABLE IF EXISTS PASSWORD;

-- ------------------------------------------------------------------
-- Create PASSWORD table.
-- ------------------------------------------------------------------
SELECT 'PASSWORD' AS "Drop Table";
CREATE TABLE PASSWORD
( PASSWORD_ID      INT UNSIGNED AUTO_INCREMENT
, USERNAME_ID      INT UNSIGNED NOT NULL
, PASSWORD         VARCHAR(10)  NOT NULL
, CREATED_BY       INT UNSIGNED NOT NULL
, CREATION_DATE    DATE         NOT NULL
, LAST_UPDATED_BY  INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE DATE         NOT NULL
, CONSTRAINT pk_password_1 PRIMARY KEY (PASSWORD_ID)
, CONSTRAINT fk_password_1 FOREIGN KEY (USERNAME_ID)     REFERENCES USERNAME(USERNAME_ID)
, CONSTRAINT fk_password_2 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_password_3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Conditionally drop objects.
SELECT 'MEMBER_INTEREST' AS "Drop Table";
DROP TABLE IF EXISTS MEMBER_INTEREST;

-- ------------------------------------------------------------------
-- Create MEMBER_INTEREST table.
-- ------------------------------------------------------------------
SELECT 'MEMBER_INTEREST' AS "Drop Table";
CREATE TABLE MEMBER_INTEREST
( MEMBER_INTEREST_ID INT UNSIGNED AUTO_INCREMENT
, MEMBER_ID          INT UNSIGNED NOT NULL
, INTEREST_ID        INT UNSIGNED NOT NULL
, CREATED_BY         INT UNSIGNED NOT NULL
, CREATION_DATE      DATE         NOT NULL
, LAST_UPDATED_BY    INT UNSIGNED NOT NULL
, LAST_UPDATE_DATE   DATE         NOT NULL
, CONSTRAINT pk_member_interest_1 PRIMARY KEY (MEMBER_INTEREST_ID)
, CONSTRAINT fk_member_interest_1 FOREIGN KEY (MEMBER_ID)       REFERENCES MEMBER(MEMBER_ID)
, CONSTRAINT fk_member_interest_2 FOREIGN KEY (INTEREST_ID)     REFERENCES INTEREST(INTEREST_ID)
, CONSTRAINT fk_member_interest_3 FOREIGN KEY (CREATED_BY)      REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
, CONSTRAINT fk_member_interest_4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES SYSTEM_USER(SYSTEM_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Commit inserts.
SELECT 'COMMIT' AS "COMMIT";
COMMIT;

-- This enables dropping tables with foreign key dependencies.
-- It is specific to the InnoDB Engine.
SELECT 'ON' AS "FOREIGN KEY CHECKS";
SET FOREIGN_KEY_CHECKS = 1;

NOTEE
